"""website in artist added

Revision ID: 7219699805e5
Revises: 3c07a7f72ee2
Create Date: 2021-01-05 22:53:04.699816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7219699805e5'
down_revision = '3c07a7f72ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
